# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: Carthage
osx_image: xcode9.4
script:
  - carthage bootstrap --platform iOS && xcodebuild test -scheme "RxOptional iOS Tests" -project RxOptional.xcodeproj -destination 'platform=iOS Simulator,name=iPhone X'
  - carthage bootstrap --platform Mac && xcodebuild test -scheme "RxOptional macOS Tests" -project RxOptional.xcodeproj -sdk 'macosx'