# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Example/Podfile
osx_image: xcode7.3
install: 
  - bundle install
  - bundle exec pod install --project-directory=Example
xcode_workspace: Example/RxOptional.xcworkspace
xcode_scheme: RxOptional Examples
xcode_sdk: iphonesimulator9.3
